parameters:
  # General parameters
  k_global: 10
  k_local: 10
  pallet_size: 20
  pallet_height: 20
  pallet_base_width: 20
  pallet_length: 20
  max_stack_height: 20
  # local criterion weights
  local_criterion_weights:
    weight_base_supports: 0.25
    weight_sides_supported: 0.05
    weight_surface_support_area: 0.10
    weight_base_height: 0.50
    weight_volume_ratio: 0.10